export const productsData: IProduct[] = ([
    {
        category: 'Наушники',
        subcategory: 'Беспроводные',
        title: 'Наушники Bose QuietComfort 35 II',
        slug: 'naushniki-bose-quietcomfort-35-ii',
        price: '79999',
        image: ['/product/image1.webp', '/product/image2.webp'],
        status: ['NEW', 'TOP_PRODUCT', 'PROMO'],
        percent_promo: 10,
        count: 25,
        short_description: 'Комфортные и качественные наушники с шумоподавлением.',
        description: 'Наушники с отличным качеством звука и эффективным шумоподавлением.',
        specifications: [
            { title: 'Тип', text: 'Беспроводные' },
            { title: 'Подключение', text: 'Bluetooth' },
            { title: 'Время работы', text: '20 часов' },
        ],
        reviews: undefined,
        instructions: 'Подключитесь через Bluetooth для использования наушников.',
    },
    {
        category: 'Наушники',
        subcategory: 'Проводные',
        title: 'Наушники Sony MDR-7506',
        slug: 'naushniki-sony-mdr-7506',
        price: '45999',
        image: ['/product/image3.webp', '/product/image4.webp'],
        status: ['TOP_PRODUCT'],
        count: 30,
        short_description: 'Профессиональные наушники с отличным звучанием.',
        description: 'Идеальны для профессионалов в звукозаписи и на сцене.',
        specifications: [
            { title: 'Тип', text: 'Проводные' },
            { title: 'Подключение', text: '3.5mm Jack' },
            { title: 'Частотный диапазон', text: '10Hz - 20kHz' },
        ],
        reviews: [
            { name: 'Дмитрий', date: '2025-02-05', text: 'Отличные наушники для записи, качественный звук.' },
            { name: 'Мария', date: '2025-02-08', text: 'Очень хорошее звучание, комфортно носить.' },
        ],
        instructions: 'Подключите наушники через 3.5mm Jack для использования.',
    },
    {
        category: 'Наушники',
        subcategory: 'Игровые',
        title: 'Наушники Razer Kraken V3',
        slug: 'naushniki-razer-kraken-v3',
        price: '24999',
        image: ['/product/image5.jpg', '/product/image6.jpg'],
        status: ['PROMO'],
        percent_promo: 15,
        count: 50,
        short_description: 'Игровые наушники с качественным звуком и микрофоном.',
        description: 'Поддержка объемного звука и синхронизация с игровыми устройствами.',
        specifications: [
            { title: 'Тип', text: 'Игровые' },
            { title: 'Подключение', text: 'USB' },
            { title: 'Особенности', text: 'Подсветка, шумоподавление' },
        ],
        reviews: [
            { name: 'Сергей', date: '2025-01-25', text: 'Отличные наушники для игры, звук просто супер.' },
            { name: 'Елена', date: '2025-01-28', text: 'Очень удобные, микрофон работает четко.' },
        ],
        instructions: 'Подключите через USB для активации подсветки и управления звуком.',
    },
    {
        category: 'Акустические системы',
        subcategory: 'Портативные колонки',
        title: 'Колонка JBL Flip 5',
        slug: 'kolonka-jbl-flip-5',
        price: '34999',
        image: ['/product/image7.jpg', '/product/image8.jpg'],
        status: ['NEW'],
        count: 100,
        short_description: 'Портативная колонка с мощным звуком и водозащитой.',
        description: 'Колонка с Bluetooth-соединением и длительным временем работы.',
        specifications: [
            { title: 'Тип', text: 'Портативная колонка' },
            { title: 'Подключение', text: 'Bluetooth' },
            { title: 'Время работы', text: '12 часов' },
        ],
        reviews: [
            { name: 'Алексей', date: '2025-02-01', text: 'Отличная колонка, звук громкий и чистый!' },
            { name: 'Марина', date: '2025-02-02', text: 'Очень довольна покупкой, водонепроницаемость работает.' },
        ],
        instructions: 'Для подключения включите Bluetooth на вашем устройстве и выберите колонку.',
    },
    {
        category: 'Акустические системы',
        subcategory: 'Саундбары',
        title: 'Саундбар Samsung HW-Q60T',
        slug: 'soundbar-samsung-hw-q60t',
        price: '74999',
        image: ['/product/image9.jpg', '/product/image10.webp'],
        count: 15,
        short_description: 'Саундбар с поддержкой Dolby Audio и превосходным качеством звука.',
        description: 'Саундбар для улучшения звучания телевизора с поддержкой Dolby Atmos.',
        specifications: [
            { title: 'Тип', text: 'Саундбар' },
            { title: 'Подключение', text: 'HDMI, Bluetooth' },
            { title: 'Мощность', text: '200 Вт' },
        ],
        reviews: [
            { name: 'Петр', date: '2025-02-10', text: 'Звук отличный, телевизор звучит намного лучше!' },
            { name: 'Ольга', date: '2025-02-12', text: 'Хороший саундбар за свою цену, звук чистый и мощный.' },
        ],
        instructions: 'Подключите саундбар к телевизору через HDMI или Bluetooth.',
    },
    {
        category: 'Акустические системы',
        subcategory: 'Домашние кинотеатры',
        title: 'Домашний кинотеатр Sony HT-S350',
        slug: 'domashniy-kinoteatr-sony-ht-s350',
        price: '59999',
        image: ['/product/image11.webp', '/product/image12.jpeg'],
        status: ['NEW'],
        count: 20,
        short_description: 'Домашний кинотеатр с мощным звуком и субвуфером.',
        description: 'Комплекс для создания кинотеатра у себя дома с отличным качеством звука.',
        specifications: [
            { title: 'Тип', text: 'Домашний кинотеатр' },
            { title: 'Мощность', text: '320 Вт' },
            { title: 'Подключение', text: 'HDMI, Bluetooth, Optical' },
        ],
        reviews: [
            { name: 'Игорь', date: '2025-02-18', text: 'Отличное качество звука, идеально для дома!' },
            { name: 'Екатерина', date: '2025-02-20', text: 'Очень крутой звук для кино и музыки.' },
        ],
        instructions: 'Подключите к телевизору через HDMI или используйте Bluetooth для подключения.',
    },
    {
        category: 'Акустические системы',
        subcategory: 'Напольные колонки',
        title: 'Напольные колонки Klipsch RP-6000F',
        slug: 'napolnye-kolonki-klipsch-rp-6000f',
        price: '159999',
        image: ['/product/image13.webp', '/product/image14.jpg'],
        count: 8,
        short_description: 'Высококачественные напольные колонки для настоящих ценителей звука.',
        description: 'Колонки с отличной акустикой и премиальным дизайном для вашего дома.',
        specifications: [
            { title: 'Тип', text: 'Напольные колонки' },
            { title: 'Мощность', text: '150 Вт' },
            { title: 'Подключение', text: 'Проводное' },
        ],
        reviews: [
            { name: 'Александр', date: '2025-02-22', text: 'Колонки просто фантастические, звук потрясающий.' },
            { name: 'Людмила', date: '2025-02-23', text: 'Дороговато, но звук того стоит.' },
        ],
        instructions: 'Подключите колонки к усилителю или ресиверу для полноценного звучания.',
    },
    {
        category: 'Усилители и ресиверы',
        subcategory: 'AV-ресиверы',
        title: 'AV-ресивер Yamaha RX-V6A',
        slug: 'av-resiver-yamaha-rx-v6a',
        price: '129999',
        image: ['/product/image15.webp', '/product/image16.webp'],
        status: ['TOP_PRODUCT'],
        count: 12,
        short_description: 'AV-ресивер с поддержкой Dolby Atmos и высокой мощностью.',
        description: 'Идеальный ресивер для построения домашнего кинотеатра с поддержкой 8K.',
        specifications: [
            { title: 'Тип', text: 'AV-ресивер' },
            { title: 'Мощность', text: '100 Вт на канал' },
            { title: 'Подключение', text: 'HDMI, Bluetooth, Wi-Fi' },
        ],
        reviews: [
            { name: 'Максим', date: '2025-02-18', text: 'Отличный ресивер, звук объемный и мощный.' },
            { name: 'Валерия', date: '2025-02-19', text: 'Простой в настройке и использовании, отличный звук.' },
        ],
        instructions: 'Подключите ресивер к телевизору и колонкам для использования.',
    },
    {
        category: 'Усилители и ресиверы',
        subcategory: 'Стереоусилители',
        title: 'Стереоусилитель Marantz PM6007',
        slug: 'stereo-usilitel-marantz-pm6007',
        price: '84999',
        image: ['/product/image17.webp', '/product/image18.jpg'],
        count: 18,
        short_description: 'Стереоусилитель с высококачественным звуком и изысканным дизайном.',
        description: 'Для аудиофилов, желающих получить чистое и мощное звучание.',
        specifications: [
            { title: 'Тип', text: 'Стереоусилитель' },
            { title: 'Мощность', text: '45 Вт на канал' },
            { title: 'Подключение', text: 'Аналоговое, цифровое' },
        ],
        reviews: [
            { name: 'Виктор', date: '2025-02-20', text: 'Чистый звук, идеально подходит для виниловых проигрывателей.' },
            { name: 'Нина', date: '2025-02-21', text: 'Очень доволен покупкой, звук на высоте.' },
        ],
        instructions: 'Подключите к вашим колонкам и источникам звука для работы.',
    },
    {
        category: 'Виниловые проигрыватели',
        subcategory: 'Автоматические',
        title: 'Виниловый проигрыватель Audio-Technica AT-LP60X',
        slug: 'vinilovy-proigrivatel-audio-technica-at-lp60x',
        price: '39999',
        image: ['/product/image19.webp', '/product/image20.webp'],
        status: ['NEW'],
        count: 45,
        short_description: 'Автоматический виниловый проигрыватель с качественным звуком.',
        description: 'Отличный выбор для начинающих коллекционеров винила.',
        specifications: [
            { title: 'Тип', text: 'Автоматический' },
            { title: 'Подключение', text: 'Аналоговое' },
            { title: 'Особенности', text: 'Автоматическая смена сторон, игла в комплекте' },
        ],
        reviews: [
            { name: 'Егор', date: '2025-02-15', text: 'Отличный проигрыватель за эту цену, звук просто великолепен.' },
            { name: 'Валентина', date: '2025-02-17', text: 'Простой и качественный проигрыватель, рекомендую.' },
        ],
        instructions: 'Подключите проигрыватель к усилителю и наслаждайтесь музыкой.',
    },
    {
        category: 'Виниловые проигрыватели',
        subcategory: 'Ручные',
        title: 'Виниловый проигрыватель Pro-Ject Debut Carbon EVO',
        slug: 'vinilovy-proigrivatel-pro-ject-debut-carbon-evo',
        price: '99999',
        image: ['/product/image21.jpg', '/product/image22.jpg'],
        count: 25,
        short_description: 'Ручной виниловый проигрыватель с углеродной стойкой и высоким качеством звука.',
        description: 'Идеальный выбор для истинных ценителей виниловой музыки.',
        specifications: [
            { title: 'Тип', text: 'Ручной' },
            { title: 'Подключение', text: 'Аналоговое' },
            { title: 'Особенности', text: 'Углеродная стойка, игла Ortofon 2M Red' },
        ],
        reviews: [
            { name: 'Денис', date: '2025-02-12', text: 'Превосходное качество звука, отличный проигрыватель.' },
            { name: 'Светлана', date: '2025-02-14', text: 'Невероятно хороший звук и стильный внешний вид.' },
        ],
        instructions: 'Подключите проигрыватель к усилителю и наслаждайтесь винилом.',
    },
    {
        category: 'Микрофоны и студийное оборудование',
        subcategory: 'Конденсаторные микрофоны',
        title: 'Микрофон Audio-Technica AT2020',
        slug: 'mikrofon-audio-technica-at2020',
        price: '24999',
        image: ['/product/image23.webp', '/product/image24.jpg'],
        status: ['NEW'],
        count: 40,
        short_description: 'Конденсаторный микрофон с отличным качеством записи.',
        description: 'Прекрасный микрофон для записи вокала и инструментов с высокой чувствительностью.',
        specifications: [
            { title: 'Тип', text: 'Конденсаторный' },
            { title: 'Частотный диапазон', text: '20Hz - 20kHz' },
            { title: 'Подключение', text: 'XLR' },
        ],
        reviews: [
            { name: 'Олег', date: '2025-02-25', text: 'Очень чистое и ровное звучание, идеально для записи.' },
            { name: 'Дарина', date: '2025-02-28', text: 'Отличный микрофон за свою цену.' },
        ],
        instructions: 'Подключите микрофон через XLR кабель к аудиоинтерфейсу для записи.',
    },
    {
        category: 'Микрофоны и студийное оборудование',
        subcategory: 'Динамические микрофоны',
        title: 'Микрофон Shure SM58',
        slug: 'mikrofon-shure-sm58',
        price: '17999',
        image: ['/product/image25.webp', '/product/image26.jpg'],
        count: 60,
        short_description: 'Динамический микрофон, идеален для вокала и сценических выступлений.',
        description: 'Микрофон для профессиональных музыкантов с исключительной надежностью.',
        specifications: [
            { title: 'Тип', text: 'Динамический' },
            { title: 'Частотный диапазон', text: '50Hz - 15kHz' },
            { title: 'Подключение', text: 'XLR' },
        ],
        reviews: [
            { name: 'Виталий', date: '2025-02-12', text: 'Легендарный микрофон, на котором выступает множество артистов.' },
            { name: 'Марина', date: '2025-02-14', text: 'Отличное качество для концертов и репетиций.' },
        ],
        instructions: 'Используйте с микшерным пультом или усилителем для достижения максимального качества.',
    },
    {
        category: 'Микрофоны и студийное оборудование',
        subcategory: 'Петличные микрофоны',
        title: 'Петличный микрофон Rode Lavalier GO',
        slug: 'petlichniy-mikrofon-rode-lavalier-go',
        price: '14999',
        image: ['/product/image27.jpg', '/product/image28.jpg'],
        count: 45,
        short_description: 'Петличный микрофон с высоким качеством звука и хорошей чувствительностью.',
        description: 'Отличный выбор для видеоблогеров и подкастеров.',
        specifications: [
            { title: 'Тип', text: 'Петличный' },
            { title: 'Частотный диапазон', text: '20Hz - 20kHz' },
            { title: 'Подключение', text: '3.5mm Jack' },
        ],
        reviews: [
            { name: 'Николай', date: '2025-02-18', text: 'Очень хороший микрофон для записи на ходу.' },
            { name: 'Ирина', date: '2025-02-20', text: 'Никаких шумов, звук чистый и ясный.' },
        ],
        instructions: 'Подключите микрофон через 3.5mm Jack к вашему устройству для записи.',
    },
    {
        category: 'Микрофоны и студийное оборудование',
        subcategory: 'Звуковые карты',
        title: 'Звуковая карта Focusrite Scarlett 2i2 3rd Gen',
        slug: 'zvukovaya-karta-focusrite-scarlett-2i2-3rd-gen',
        price: '29999',
        image: ['/product/image29.webp', '/product/image30.webp'],
        count: 35,
        short_description: 'Звуковая карта с двумя входами для профессиональной записи.',
        description: 'Идеально подходит для студийной записи и работы с подкастами.',
        specifications: [
            { title: 'Тип', text: 'Звуковая карта' },
            { title: 'Входы', text: '2 x XLR/Jack' },
            { title: 'Подключение', text: 'USB 2.0' },
        ],
        reviews: [
            { name: 'Антон', date: '2025-02-22', text: 'Прекрасная звуковая карта для записи вокала и инструментов.' },
            { name: 'Светлана', date: '2025-02-24', text: 'Очень качественная карта, звук кристально чистый.' },
        ],
        instructions: 'Подключите звуковую карту к ПК через USB и настройте с помощью драйверов.',
    },
    {
        category: 'Микрофоны и студийное оборудование',
        subcategory: 'Стойки и аксессуары',
        title: 'Стойка для микрофона Neewer NW-35',
        slug: 'stoyka-dlya-mikrofona-neewer-nw-35',
        price: '4999',
        image: ['/product/image31.webp', '/product/image32.jpg'],
        count: 70,
        short_description: 'Стойка для микрофона с хорошей регулировкой высоты и угла наклона.',
        description: 'Удобная стойка для студийных микрофонов с прочной конструкцией.',
        specifications: [
            { title: 'Тип', text: 'Стойка для микрофона' },
            { title: 'Материал', text: 'Металл' },
            { title: 'Регулировка', text: 'Высота и угол наклона' },
        ],
        reviews: [
            { name: 'Андрей', date: '2025-02-26', text: 'Отличная стойка, удобная и устойчивая.' },
            { name: 'Юлия', date: '2025-02-27', text: 'Легко настраивается, подходит для большинства микрофонов.' },
        ],
        instructions: 'Регулируйте высоту и угол наклона стойки для комфортной работы с микрофоном.',
    },
    {
        category: 'Усилители и ресиверы',
        subcategory: 'Гибридные усилители',
        title: 'Гибридный усилитель Audio Research VSi60',
        slug: 'gibridny-usilitel-audio-research-vsi60',
        price: '399999',
        image: ['/product/image33.webp', '/product/image34.jpg'],
        count: 5,
        short_description: 'Гибридный усилитель с ламповым и транзисторным выходом.',
        description: 'Комбинированный усилитель для аудиофилов с качественным звучанием.',
        specifications: [
            { title: 'Тип', text: 'Гибридный усилитель' },
            { title: 'Мощность', text: '60 Вт' },
            { title: 'Подключение', text: 'Аналоговое' },
        ],
        reviews: [
            { name: 'Дмитрий', date: '2025-02-20', text: 'Звук просто невероятный, идеально для качественной записи и прослушивания.' },
            { name: 'Юлия', date: '2025-02-21', text: 'Потрясающий усилитель, звучание как в студии.' },
        ],
        instructions: 'Подключите усилитель к вашим колонкам и источникам звука для использования.',
    },
    {
        category: 'Наушники',
        subcategory: 'Студийные',
        title: 'Наушники Beyerdynamic DT 770 PRO',
        slug: 'naushniki-beyerdynamic-dt-770-pro',
        price: '59999',
        image: ['/product/image35.webp', '/product/image36.jpg'],
        status: ['NEW'],
        count: 20,
        short_description: 'Профессиональные закрытые наушники для студийного мониторинга.',
        description: 'Идеально подходят для звукозаписи и работы в студии.',
        specifications: [
            { title: 'Тип', text: 'Студийные' },
            { title: 'Подключение', text: '3.5mm Jack' },
            { title: 'Частотный диапазон', text: '5Hz - 35kHz' },
        ],
        reviews: [
            { name: 'Андрей', date: '2025-03-01', text: 'Очень детальный звук, идеально для сведения.' },
            { name: 'Елена', date: '2025-03-02', text: 'Комфортные и с отличной изоляцией от шума.' },
        ],
        instructions: 'Подключите к аудиоинтерфейсу или компьютеру через 3.5mm Jack.',
    },
    {
        category: 'Акустические системы',
        subcategory: 'Студийные мониторы',
        title: 'Студийные мониторы KRK Rokit 5 G4',
        slug: 'studiynye-monitory-krk-rokit-5-g4',
        price: '79999',
        image: ['/product/image37.webp', '/product/image38.jpg'],
        count: 10,
        short_description: 'Популярные студийные мониторы с чистым звуком и мощными низами.',
        description: 'Используются профессионалами для сведения и мастеринга.',
        specifications: [
            { title: 'Тип', text: 'Активные студийные мониторы' },
            { title: 'Подключение', text: 'XLR, TRS' },
            { title: 'Мощность', text: '55 Вт' },
        ],
        reviews: [
            { name: 'Максим', date: '2025-03-05', text: 'Звук кристально чистый, отличные для работы в студии.' },
            { name: 'Анна', date: '2025-03-06', text: 'Очень мощные, но при этом точные мониторы.' },
        ],
        instructions: 'Подключите через XLR/TRS для оптимального звучания.',
    },
    {
        category: 'Усилители и ресиверы',
        subcategory: 'Ламповый звук',
        title: 'Ламповый усилитель Line Magnetic LM-518IA',
        slug: 'lampovyy-usilitel-line-magnetic-lm-518ia',
        price: '499999',
        image: ['/product/image39.webp', '/product/image40.webp'],
        count: 3,
        short_description: 'Ламповый усилитель класса А с невероятной детализацией звука.',
        description: 'Ручная сборка, премиальные компоненты и винтажный дизайн.',
        specifications: [
            { title: 'Тип', text: 'Ламповый усилитель' },
            { title: 'Мощность', text: '22 Вт' },
            { title: 'Подключение', text: 'Аналоговое' },
        ],
        reviews: [
            { name: 'Владимир', date: '2025-03-10', text: 'Лучший ламповый звук, который я слышал!' },
            { name: 'Сергей', date: '2025-03-12', text: 'Детализация просто на высоте, очень доволен покупкой.' },
        ],
        instructions: 'Подключите к акустическим системам высокого класса.',
    },
    {
        category: 'Виниловые проигрыватели',
        subcategory: 'DJ-вертушки',
        title: 'DJ-вертушка Pioneer PLX-1000',
        slug: 'dj-vertushka-pioneer-plx-1000',
        price: '299999',
        image: ['/product/image41.webp', '/product/image42.webp'],
        count: 8,
        short_description: 'Профессиональная DJ-вертушка с точной регулировкой скорости.',
        description: 'Разработана для клубного использования и домашних студий.',
        specifications: [
            { title: 'Тип', text: 'DJ-вертушка' },
            { title: 'Привод', text: 'Прямой' },
            { title: 'Диапазон темпа', text: '±8%, ±16%, ±50%' },
        ],
        reviews: [
            { name: 'Артур', date: '2025-03-14', text: 'Идеальный контроль скорости, очень удобная.' },
            { name: 'Михаил', date: '2025-03-15', text: 'Звучит просто потрясающе, лучшая в своем классе.' },
        ],
        instructions: 'Используйте с микшером для выступлений или записи.',
    },
    {
        category: 'Микрофоны и студийное оборудование',
        subcategory: 'Звуковые карты',
        title: 'Звуковая карта Universal Audio Apollo Twin X',
        slug: 'zvukovaya-karta-universal-audio-apollo-twin-x',
        price: '449999',
        image: ['/product/image43.jpg', '/product/image44.jpg'],
        count: 6,
        short_description: 'Профессиональная звуковая карта с поддержкой плагинов UAD.',
        description: 'Идеальный выбор для студийной работы и продвинутых записей.',
        specifications: [
            { title: 'Тип', text: 'Звуковая карта' },
            { title: 'Подключение', text: 'Thunderbolt 3' },
            { title: 'Количество входов', text: '2' },
        ],
        reviews: [
            { name: 'Даниил', date: '2025-03-18', text: 'Просто топовая карта, звук невероятный.' },
            { name: 'Анастасия', date: '2025-03-19', text: 'Плагины UAD реально делают звук профессиональным.' },
        ],
        instructions: 'Подключите через Thunderbolt 3 и настройте в DAW.',
    },
    {
        category: 'Виниловые проигрыватели',
        subcategory: 'С встроенным усилителем',
        title: 'Проигрыватель TEAC TN-280BT',
        slug: 'proigryvatel-teac-tn-280bt',
        price: '169999',
        image: ['/product/image45.webp', '/product/image46.webp'],
        count: 12,
        short_description: 'Виниловый проигрыватель с встроенным фонокорректором и Bluetooth.',
        description: 'Простота в использовании, отличное качество звучания, беспроводное соединение.',
        specifications: [
            { title: 'Тип', text: 'Полуавтоматический' },
            { title: 'Подключение', text: 'Bluetooth, RCA' },
            { title: 'Привод', text: 'Ременной' },
        ],
        reviews: [
            { name: 'Евгений', date: '2025-03-21', text: 'Очень удобный проигрыватель, без проводов звучит отлично.' },
            { name: 'Оксана', date: '2025-03-22', text: 'Фонокорректор встроенный - это просто супер, звук шикарный!' },
        ],
        instructions: 'Подключите к колонкам через Bluetooth или RCA-кабель.',
    },
    {
        category: 'Наушники',
        subcategory: 'Спортивные',
        title: 'Наушники JBL Endurance Peak 3',
        slug: 'naushniki-jbl-endurance-peak-3',
        price: '49999',
        image: ['/product/image47.webp', '/product/image48.jpg'],
        status: ['NEW', 'TOP_PRODUCT', 'PROMO'],
        percent_promo: 15,
        count: 30,
        short_description: 'Спортивные беспроводные наушники с влагозащитой и мощным звуком.',
        description: 'Надёжная посадка, водонепроницаемость IPX7, удобное управление.',
        specifications: [
            { title: 'Тип', text: 'Спортивные' },
            { title: 'Подключение', text: 'Bluetooth' },
            { title: 'Время работы', text: '30 часов' },
        ],
        reviews: [
            { name: 'Виталий', date: '2025-03-25', text: 'Отлично держатся в ушах, звук просто супер!' },
            { name: 'Марина', date: '2025-03-26', text: 'Идеальны для пробежек, долго держат заряд.' },
        ],
        instructions: 'Зарядите наушники перед использованием, подключитесь через Bluetooth.',
    },
    {
        category: 'Акустические системы',
        subcategory: 'Напольные колонки',
        title: 'Напольные колонки DALI Oberon 7',
        slug: 'napolnye-kolonki-dali-oberon-7',
        price: '299999',
        image: ['/product/image49.webp', '/product/image50.jpg'],
        count: 5,
        short_description: 'Мощные напольные колонки с великолепной акустикой.',
        description: 'Идеальны для домашнего прослушивания музыки в высоком качестве.',
        specifications: [
            { title: 'Тип', text: 'Напольные колонки' },
            { title: 'Мощность', text: '150 Вт' },
            { title: 'Подключение', text: 'Проводное' },
        ],
        reviews: [
            { name: 'Роман', date: '2025-03-28', text: 'Очень объемный звук, бас мощный и глубокий.' },
            { name: 'Анжелика', date: '2025-03-29', text: 'Слушаю классику, звук чистый и приятный!' },
        ],
        instructions: 'Подключите к усилителю для достижения лучшего звука.',
    },
    {
        category: 'Усилители и ресиверы',
        subcategory: 'ЦАП и предусилители',
        title: 'ЦАП Chord Mojo 2',
        slug: 'cap-chord-mojo-2',
        price: '249999',
        image: ['/product/image51.webp', '/product/image52.webp'],
        count: 8,
        short_description: 'Цифро-аналоговый преобразователь с выдающимся звуком.',
        description: 'Компактный, но мощный ЦАП для качественного прослушивания музыки.',
        specifications: [
            { title: 'Тип', text: 'ЦАП' },
            { title: 'Подключение', text: 'USB, Optical, Coaxial' },
            { title: 'Разрядность', text: '32 бит / 768 кГц' },
        ],
        reviews: [
            { name: 'Глеб', date: '2025-04-01', text: 'Звук стал просто невероятным, детализация высочайшая!' },
            { name: 'Юлия', date: '2025-04-02', text: 'Компактный, удобный, звук потрясающий!' },
        ],
        instructions: 'Подключите к источнику звука через USB или оптический вход.',
    },
    {
        category: 'Микрофоны и студийное оборудование',
        subcategory: 'Стойки и аксессуары',
        title: 'Стойка для микрофона K&M 210/9',
        slug: 'stoyka-dlya-mikrofona-km-210-9',
        price: '24999',
        image: ['/product/image53.webp', '/product/image54.jpeg'],
        count: 15,
        short_description: 'Универсальная стойка для микрофона с регулируемым наклоном.',
        description: 'Прочная и устойчивая стойка, идеальна для студийной работы.',
        specifications: [
            { title: 'Тип', text: 'Стойка для микрофона' },
            { title: 'Материал', text: 'Металл' },
            { title: 'Регулировка', text: 'Высота и угол наклона' },
        ],
        reviews: [
            { name: 'Николай', date: '2025-04-04', text: 'Прочная конструкция, не падает, очень удобная.' },
            { name: 'Олег', date: '2025-04-05', text: 'Отлично подходит для студии и репетиций.' },
        ],
        instructions: 'Настройте высоту и угол наклона перед использованием.',
    },
    {
        category: 'Акустические системы',
        subcategory: 'Домашние кинотеатры',
        title: 'Домашний кинотеатр Yamaha RX-V385',
        slug: 'domashniy-kinoteatr-yamaha-rx-v385',
        price: '189999',
        image: ['/product/image55.webp', '/product/image56.webp'],
        count: 7,
        short_description: 'Домашний кинотеатр 5.1 с качественным объемным звуком.',
        description: 'Мощный ресивер и акустика для настоящего погружения в фильмы.',
        specifications: [
            { title: 'Тип', text: 'Домашний кинотеатр 5.1' },
            { title: 'Мощность', text: '250 Вт' },
            { title: 'Подключение', text: 'HDMI, Bluetooth' },
        ],
        reviews: [
            { name: 'Иван', date: '2025-04-07', text: 'Очень классный звук, прям как в кинотеатре!' },
            { name: 'Анна', date: '2025-04-08', text: 'Удобное подключение, всё работает отлично.' },
        ],
        instructions: 'Подключите через HDMI и настройте колонки для оптимального звучания.',
    },
    {
        category: 'Наушники',
        subcategory: 'Проводные',
        title: 'Наушники Sennheiser HD 660S',
        slug: 'naushniki-sennheiser-hd-660s',
        price: '199999',
        image: ['/product/image57.webp', '/product/image58.jpg'],
        status: ['TOP_PRODUCT', 'PROMO'],
        percent_promo: 23,
        count: 10,
        short_description: 'Аудиофильские открытые наушники с детализированным звуком.',
        description: 'Чистый и естественный звук, идеален для меломанов и профессионалов.',
        specifications: [
            { title: 'Тип', text: 'Открытые' },
            { title: 'Подключение', text: '3.5mm Jack, 6.3mm Jack' },
            { title: 'Частотный диапазон', text: '10Hz - 41kHz' },
        ],
        reviews: [
            { name: 'Александр', date: '2025-04-10', text: 'Звук невероятный, детализация и сцена на высоте!' },
            { name: 'Дмитрий', date: '2025-04-12', text: 'Очень комфортные, можно слушать часами.' },
        ],
        instructions: 'Подключите к качественному усилителю для максимального звучания.',
    },
    {
        category: 'Акустические системы',
        subcategory: 'Портативные колонки',
        title: 'Портативная колонка Sony SRS-XB43',
        slug: 'portativnaya-kolonka-sony-srs-xb43',
        price: '99999',
        image: ['/product/image59.webp', '/product/image60.webp'],
        status: ['PROMO'],
        percent_promo: 15,
        count: 25,
        short_description: 'Мощная портативная колонка с глубоки басами и светомузыкой.',
        description: 'Идеальный выбор для вечеринок и поездок на природу.',
        specifications: [
            { title: 'Тип', text: 'Портативная колонка' },
            { title: 'Подключение', text: 'Bluetooth, NFC' },
            { title: 'Время работы', text: '24 часа' },
        ],
        reviews: [
            { name: 'Максим', date: '2025-04-15', text: 'Отличный звук, мощные басы, вечеринка удалась!' },
            { name: 'Марина', date: '2025-04-17', text: 'Очень нравится подсветка, создает настроение.' },
        ],
        instructions: 'Включите колонку, подключитесь по Bluetooth и наслаждайтесь музыкой.',
    },
    {
        category: 'Виниловые проигрыватели',
        subcategory: 'Ручные',
        title: 'Проигрыватель Rega Planar 3',
        slug: 'proigryvatel-rega-planar-3',
        price: '249999',
        image: ['/product/image61.webp', '/product/image62.jpg'],
        count: 8,
        short_description: 'Высококачественный ручной виниловый проигрыватель.',
        description: 'Проигрыватель для аудиофилов с минимальными вибрациями и чистым звуком.',
        specifications: [
            { title: 'Тип', text: 'Ручной' },
            { title: 'Привод', text: 'Ременной' },
            { title: 'Подключение', text: 'RCA' },
        ],
        reviews: [
            { name: 'Сергей', date: '2025-04-18', text: 'Лучший проигрыватель за эти деньги, звук невероятный!' },
            { name: 'Ольга', date: '2025-04-19', text: 'Очень чистый звук, отличный дизайн.' },
        ],
        instructions: 'Используйте качественную виниловую пластинку и настройте баланс тонарма.',
    },
    {
        category: 'Микрофоны и студийное оборудование',
        subcategory: 'Конденсаторные микрофоны',
        title: 'Микрофон Rode NT1-A',
        slug: 'mikrofon-rode-nt1-a',
        price: '129999',
        image: ['/product/image63.webp', '/product/image64.jpg'],
        count: 12,
        short_description: 'Конденсаторный микрофон с низким уровнем шума.',
        description: 'Идеален для студийной записи вокала и инструментов.',
        specifications: [
            { title: 'Тип', text: 'Конденсаторный' },
            { title: 'Частотный диапазон', text: '20Hz - 20kHz' },
            { title: 'Подключение', text: 'XLR' },
        ],
        reviews: [
            { name: 'Глеб', date: '2025-04-20', text: 'Записываю вокал, звук очень чистый, рекомендую!' },
            { name: 'Анастасия', date: '2025-04-21', text: 'Очень качественная сборка и звук без шумов.' },
        ],
        instructions: 'Подключите к аудиоинтерфейсу через XLR и настройте гейн.',
    },
    {
        category: 'Усилители и ресиверы',
        subcategory: 'Стереоусилители',
        title: 'Стереоусилитель Cambridge Audio CXA81',
        slug: 'stereo-usilitel-cambridge-audio-cxa81',
        price: '349999',
        image: ['/product/image65.webp', '/product/image66.webp'],
        count: 6,
        short_description: 'Мощный стереоусилитель с поддержкой высокого разрешения звука.',
        description: 'Идеален для аудиофилов, выдаёт мощный и детальный звук.',
        specifications: [
            { title: 'Тип', text: 'Стереоусилитель' },
            { title: 'Мощность', text: '80 Вт на канал' },
            { title: 'Подключение', text: 'RCA, XLR, Bluetooth' },
        ],
        reviews: [
            { name: 'Денис', date: '2025-04-22', text: 'Звучание просто бомбическое, раскрывает колонки на 100%.' },
            { name: 'Виктор', date: '2025-04-23', text: 'Очень мощный и чистый звук, доволен покупкой!' },
        ],
        instructions: 'Подключите к акустическим системам высокого уровня для лучшего результата.',
    }
] as IProduct[]).map(product => ({
    ...product,
    slug_category: generateSlug(product.category),
    slug_subcategory: generateSlug(product.subcategory)
}));


function transliterate(text: string): string {
    const map: Record<string, string> = {
        'а': 'a', 'б': 'b', 'в': 'v', 'г': 'g', 'д': 'd', 'е': 'e', 'ё': 'yo', 'ж': 'zh',
        'з': 'z', 'и': 'i', 'й': 'y', 'к': 'k', 'л': 'l', 'м': 'm', 'н': 'n', 'о': 'o',
        'п': 'p', 'р': 'r', 'с': 's', 'т': 't', 'у': 'u', 'ф': 'f', 'х': 'kh', 'ц': 'ts',
        'ч': 'ch', 'ш': 'sh', 'щ': 'shch', 'ъ': '', 'ы': 'y', 'ь': '', 'э': 'e', 'ю': 'yu', 'я': 'ya'
    };
    return text.split('').map(char => map[char.toLowerCase()] || char).join('');
}

function generateSlug(text: string): string {
    return transliterate(text)
        .toLowerCase()
        .replace(/\s+/g, '-')
        .replace(/[^a-z0-9-]/g, '')
        .replace(/-+/g, '-')
        .trim();
}


