export const productsData: IProduct[] = [
    {
        category: 'Наушники',
        subcategory: 'Беспроводные',
        title: 'Наушники Bose QuietComfort 35 II',
        slug: 'naushniki-bose-quietcomfort-35-ii',
        price: '79999',
        image: ['/product/image1.webp', '/product/image2.webp'],
        status: ['NEW'],
        percent_promo: 10,
        count: 25,
        short_description: 'Комфортные и качественные наушники с шумоподавлением.',
        description: 'Наушники с отличным качеством звука и эффективным шумоподавлением.',
        specifications: [
            { title: 'Тип', text: 'Беспроводные' },
            { title: 'Подключение', text: 'Bluetooth' },
            { title: 'Время работы', text: '20 часов' },
        ],
        reviews: [
            { name: 'Иван', date: '2025-01-15', text: 'Отличные наушники, качественный звук!' },
            { name: 'Анна', date: '2025-01-17', text: 'Очень удобные, шумоподавление работает хорошо.' },
        ],
        instructions: 'Подключитесь через Bluetooth для использования наушников.',
    },
    {
        category: 'Наушники',
        subcategory: 'Проводные',
        title: 'Наушники Sony MDR-7506',
        slug: 'naushniki-sony-mdr-7506',
        price: '45999',
        image: ['/product/image3.webp', '/product/image4.webp'],
        status: ['TOP_PRODUCT'],
        count: 30,
        short_description: 'Профессиональные наушники с отличным звучанием.',
        description: 'Идеальны для профессионалов в звукозаписи и на сцене.',
        specifications: [
            { title: 'Тип', text: 'Проводные' },
            { title: 'Подключение', text: '3.5mm Jack' },
            { title: 'Частотный диапазон', text: '10Hz - 20kHz' },
        ],
        reviews: [
            { name: 'Дмитрий', date: '2025-02-05', text: 'Отличные наушники для записи, качественный звук.' },
            { name: 'Мария', date: '2025-02-08', text: 'Очень хорошее звучание, комфортно носить.' },
        ],
        instructions: 'Подключите наушники через 3.5mm Jack для использования.',
    },
    {
        category: 'Наушники',
        subcategory: 'Игровые',
        title: 'Наушники Razer Kraken V3',
        slug: 'naushniki-razer-kraken-v3',
        price: '24999',
        image: ['/product/image5.jpg', '/product/image6.jpg'],
        status: ['PROMO'],
        percent_promo: 15,
        count: 50,
        short_description: 'Игровые наушники с качественным звуком и микрофоном.',
        description: 'Поддержка объемного звука и синхронизация с игровыми устройствами.',
        specifications: [
            { title: 'Тип', text: 'Игровые' },
            { title: 'Подключение', text: 'USB' },
            { title: 'Особенности', text: 'Подсветка, шумоподавление' },
        ],
        reviews: [
            { name: 'Сергей', date: '2025-01-25', text: 'Отличные наушники для игры, звук просто супер.' },
            { name: 'Елена', date: '2025-01-28', text: 'Очень удобные, микрофон работает четко.' },
        ],
        instructions: 'Подключите через USB для активации подсветки и управления звуком.',
    },
    {
        category: 'Акустические системы',
        subcategory: 'Портативные колонки',
        title: 'Колонка JBL Flip 5',
        slug: 'kolonka-jbl-flip-5',
        price: '34999',
        image: ['/product/image7.jpg', '/product/image8.jpg'],
        status: ['NEW'],
        count: 100,
        short_description: 'Портативная колонка с мощным звуком и водозащитой.',
        description: 'Колонка с Bluetooth-соединением и длительным временем работы.',
        specifications: [
            { title: 'Тип', text: 'Портативная колонка' },
            { title: 'Подключение', text: 'Bluetooth' },
            { title: 'Время работы', text: '12 часов' },
        ],
        reviews: [
            { name: 'Алексей', date: '2025-02-01', text: 'Отличная колонка, звук громкий и чистый!' },
            { name: 'Марина', date: '2025-02-02', text: 'Очень довольна покупкой, водонепроницаемость работает.' },
        ],
        instructions: 'Для подключения включите Bluetooth на вашем устройстве и выберите колонку.',
    },
    {
        category: 'Акустические системы',
        subcategory: 'Саундбары',
        title: 'Саундбар Samsung HW-Q60T',
        slug: 'soundbar-samsung-hw-q60t',
        price: '74999',
        image: ['/product/image9.jpg', '/product/image10.webp'],
        count: 15,
        short_description: 'Саундбар с поддержкой Dolby Audio и превосходным качеством звука.',
        description: 'Саундбар для улучшения звучания телевизора с поддержкой Dolby Atmos.',
        specifications: [
            { title: 'Тип', text: 'Саундбар' },
            { title: 'Подключение', text: 'HDMI, Bluetooth' },
            { title: 'Мощность', text: '200 Вт' },
        ],
        reviews: [
            { name: 'Петр', date: '2025-02-10', text: 'Звук отличный, телевизор звучит намного лучше!' },
            { name: 'Ольга', date: '2025-02-12', text: 'Хороший саундбар за свою цену, звук чистый и мощный.' },
        ],
        instructions: 'Подключите саундбар к телевизору через HDMI или Bluetooth.',
    },
    {
        category: 'Акустические системы',
        subcategory: 'Домашние кинотеатры',
        title: 'Домашний кинотеатр Sony HT-S350',
        slug: 'domashniy-kinoteatr-sony-ht-s350',
        price: '59999',
        image: ['/product/image11.webp', '/product/image12.jpeg'],
        status: ['NEW'],
        count: 20,
        short_description: 'Домашний кинотеатр с мощным звуком и субвуфером.',
        description: 'Комплекс для создания кинотеатра у себя дома с отличным качеством звука.',
        specifications: [
            { title: 'Тип', text: 'Домашний кинотеатр' },
            { title: 'Мощность', text: '320 Вт' },
            { title: 'Подключение', text: 'HDMI, Bluetooth, Optical' },
        ],
        reviews: [
            { name: 'Игорь', date: '2025-02-18', text: 'Отличное качество звука, идеально для дома!' },
            { name: 'Екатерина', date: '2025-02-20', text: 'Очень крутой звук для кино и музыки.' },
        ],
        instructions: 'Подключите к телевизору через HDMI или используйте Bluetooth для подключения.',
    },
    {
        category: 'Акустические системы',
        subcategory: 'Напольные колонки',
        title: 'Напольные колонки Klipsch RP-6000F',
        slug: 'napolnye-kolonki-klipsch-rp-6000f',
        price: '159999',
        image: ['/product/image13.webp', '/product/image14.jpg'],
        count: 8,
        short_description: 'Высококачественные напольные колонки для настоящих ценителей звука.',
        description: 'Колонки с отличной акустикой и премиальным дизайном для вашего дома.',
        specifications: [
            { title: 'Тип', text: 'Напольные колонки' },
            { title: 'Мощность', text: '150 Вт' },
            { title: 'Подключение', text: 'Проводное' },
        ],
        reviews: [
            { name: 'Александр', date: '2025-02-22', text: 'Колонки просто фантастические, звук потрясающий.' },
            { name: 'Людмила', date: '2025-02-23', text: 'Дороговато, но звук того стоит.' },
        ],
        instructions: 'Подключите колонки к усилителю или ресиверу для полноценного звучания.',
    },
    {
        category: 'Усилители и ресиверы',
        subcategory: 'AV-ресиверы',
        title: 'AV-ресивер Yamaha RX-V6A',
        slug: 'av-resiver-yamaha-rx-v6a',
        price: '129999',
        image: ['/product/image15.webp', '/product/image16.webp'],
        status: ['TOP_PRODUCT'],
        count: 12,
        short_description: 'AV-ресивер с поддержкой Dolby Atmos и высокой мощностью.',
        description: 'Идеальный ресивер для построения домашнего кинотеатра с поддержкой 8K.',
        specifications: [
            { title: 'Тип', text: 'AV-ресивер' },
            { title: 'Мощность', text: '100 Вт на канал' },
            { title: 'Подключение', text: 'HDMI, Bluetooth, Wi-Fi' },
        ],
        reviews: [
            { name: 'Максим', date: '2025-02-18', text: 'Отличный ресивер, звук объемный и мощный.' },
            { name: 'Валерия', date: '2025-02-19', text: 'Простой в настройке и использовании, отличный звук.' },
        ],
        instructions: 'Подключите ресивер к телевизору и колонкам для использования.',
    },
    {
        category: 'Усилители и ресиверы',
        subcategory: 'Стереоусилители',
        title: 'Стереоусилитель Marantz PM6007',
        slug: 'stereo-usilitel-marantz-pm6007',
        price: '84999',
        image: ['/product/image17.webp', '/product/image18.jpg'],
        count: 18,
        short_description: 'Стереоусилитель с высококачественным звуком и изысканным дизайном.',
        description: 'Для аудиофилов, желающих получить чистое и мощное звучание.',
        specifications: [
            { title: 'Тип', text: 'Стереоусилитель' },
            { title: 'Мощность', text: '45 Вт на канал' },
            { title: 'Подключение', text: 'Аналоговое, цифровое' },
        ],
        reviews: [
            { name: 'Виктор', date: '2025-02-20', text: 'Чистый звук, идеально подходит для виниловых проигрывателей.' },
            { name: 'Нина', date: '2025-02-21', text: 'Очень доволен покупкой, звук на высоте.' },
        ],
        instructions: 'Подключите к вашим колонкам и источникам звука для работы.',
    },
    {
        category: 'Виниловые проигрыватели',
        subcategory: 'Автоматические',
        title: 'Виниловый проигрыватель Audio-Technica AT-LP60X',
        slug: 'vinilovy-proigrivatel-audio-technica-at-lp60x',
        price: '39999',
        image: ['/product/image19.webp', '/product/image20.webp'],
        status: ['NEW'],
        count: 45,
        short_description: 'Автоматический виниловый проигрыватель с качественным звуком.',
        description: 'Отличный выбор для начинающих коллекционеров винила.',
        specifications: [
            { title: 'Тип', text: 'Автоматический' },
            { title: 'Подключение', text: 'Аналоговое' },
            { title: 'Особенности', text: 'Автоматическая смена сторон, игла в комплекте' },
        ],
        reviews: [
            { name: 'Егор', date: '2025-02-15', text: 'Отличный проигрыватель за эту цену, звук просто великолепен.' },
            { name: 'Валентина', date: '2025-02-17', text: 'Простой и качественный проигрыватель, рекомендую.' },
        ],
        instructions: 'Подключите проигрыватель к усилителю и наслаждайтесь музыкой.',
    },
    {
        category: 'Виниловые проигрыватели',
        subcategory: 'Ручные',
        title: 'Виниловый проигрыватель Pro-Ject Debut Carbon EVO',
        slug: 'vinilovy-proigrivatel-pro-ject-debut-carbon-evo',
        price: '99999',
        image: ['/product/image21.jpg', '/product/image22.jpg'],
        count: 25,
        short_description: 'Ручной виниловый проигрыватель с углеродной стойкой и высоким качеством звука.',
        description: 'Идеальный выбор для истинных ценителей виниловой музыки.',
        specifications: [
            { title: 'Тип', text: 'Ручной' },
            { title: 'Подключение', text: 'Аналоговое' },
            { title: 'Особенности', text: 'Углеродная стойка, игла Ortofon 2M Red' },
        ],
        reviews: [
            { name: 'Денис', date: '2025-02-12', text: 'Превосходное качество звука, отличный проигрыватель.' },
            { name: 'Светлана', date: '2025-02-14', text: 'Невероятно хороший звук и стильный внешний вид.' },
        ],
        instructions: 'Подключите проигрыватель к усилителю и наслаждайтесь винилом.',
    },
    {
        category: 'Микрофоны и студийное оборудование',
        subcategory: 'Конденсаторные микрофоны',
        title: 'Микрофон Audio-Technica AT2020',
        slug: 'mikrofon-audio-technica-at2020',
        price: '24999',
        image: ['/product/image23.webp', '/product/image24.jpg'],
        status: ['NEW'],
        count: 40,
        short_description: 'Конденсаторный микрофон с отличным качеством записи.',
        description: 'Прекрасный микрофон для записи вокала и инструментов с высокой чувствительностью.',
        specifications: [
            { title: 'Тип', text: 'Конденсаторный' },
            { title: 'Частотный диапазон', text: '20Hz - 20kHz' },
            { title: 'Подключение', text: 'XLR' },
        ],
        reviews: [
            { name: 'Олег', date: '2025-02-25', text: 'Очень чистое и ровное звучание, идеально для записи.' },
            { name: 'Дарина', date: '2025-02-28', text: 'Отличный микрофон за свою цену.' },
        ],
        instructions: 'Подключите микрофон через XLR кабель к аудиоинтерфейсу для записи.',
    },
    {
        category: 'Микрофоны и студийное оборудование',
        subcategory: 'Динамические микрофоны',
        title: 'Микрофон Shure SM58',
        slug: 'mikrofon-shure-sm58',
        price: '17999',
        image: ['/product/image25.webp', '/product/image26.jpg'],
        count: 60,
        short_description: 'Динамический микрофон, идеален для вокала и сценических выступлений.',
        description: 'Микрофон для профессиональных музыкантов с исключительной надежностью.',
        specifications: [
            { title: 'Тип', text: 'Динамический' },
            { title: 'Частотный диапазон', text: '50Hz - 15kHz' },
            { title: 'Подключение', text: 'XLR' },
        ],
        reviews: [
            { name: 'Виталий', date: '2025-02-12', text: 'Легендарный микрофон, на котором выступает множество артистов.' },
            { name: 'Марина', date: '2025-02-14', text: 'Отличное качество для концертов и репетиций.' },
        ],
        instructions: 'Используйте с микшерным пультом или усилителем для достижения максимального качества.',
    },
    {
        category: 'Микрофоны и студийное оборудование',
        subcategory: 'Петличные микрофоны',
        title: 'Петличный микрофон Rode Lavalier GO',
        slug: 'petlichniy-mikrofon-rode-lavalier-go',
        price: '14999',
        image: ['/product/image27.jpg', '/product/image28.jpg'],
        count: 45,
        short_description: 'Петличный микрофон с высоким качеством звука и хорошей чувствительностью.',
        description: 'Отличный выбор для видеоблогеров и подкастеров.',
        specifications: [
            { title: 'Тип', text: 'Петличный' },
            { title: 'Частотный диапазон', text: '20Hz - 20kHz' },
            { title: 'Подключение', text: '3.5mm Jack' },
        ],
        reviews: [
            { name: 'Николай', date: '2025-02-18', text: 'Очень хороший микрофон для записи на ходу.' },
            { name: 'Ирина', date: '2025-02-20', text: 'Никаких шумов, звук чистый и ясный.' },
        ],
        instructions: 'Подключите микрофон через 3.5mm Jack к вашему устройству для записи.',
    },
    {
        category: 'Микрофоны и студийное оборудование',
        subcategory: 'Звуковые карты',
        title: 'Звуковая карта Focusrite Scarlett 2i2 3rd Gen',
        slug: 'zvukovaya-karta-focusrite-scarlett-2i2-3rd-gen',
        price: '29999',
        image: ['/product/image29.webp', '/product/image30.webp'],
        count: 35,
        short_description: 'Звуковая карта с двумя входами для профессиональной записи.',
        description: 'Идеально подходит для студийной записи и работы с подкастами.',
        specifications: [
            { title: 'Тип', text: 'Звуковая карта' },
            { title: 'Входы', text: '2 x XLR/Jack' },
            { title: 'Подключение', text: 'USB 2.0' },
        ],
        reviews: [
            { name: 'Антон', date: '2025-02-22', text: 'Прекрасная звуковая карта для записи вокала и инструментов.' },
            { name: 'Светлана', date: '2025-02-24', text: 'Очень качественная карта, звук кристально чистый.' },
        ],
        instructions: 'Подключите звуковую карту к ПК через USB и настройте с помощью драйверов.',
    },
    {
        category: 'Микрофоны и студийное оборудование',
        subcategory: 'Стойки и аксессуары',
        title: 'Стойка для микрофона Neewer NW-35',
        slug: 'stoyka-dlya-mikrofona-neewer-nw-35',
        price: '4999',
        image: ['/product/image31.webp', '/product/image32.jpg'],
        count: 70,
        short_description: 'Стойка для микрофона с хорошей регулировкой высоты и угла наклона.',
        description: 'Удобная стойка для студийных микрофонов с прочной конструкцией.',
        specifications: [
            { title: 'Тип', text: 'Стойка для микрофона' },
            { title: 'Материал', text: 'Металл' },
            { title: 'Регулировка', text: 'Высота и угол наклона' },
        ],
        reviews: [
            { name: 'Андрей', date: '2025-02-26', text: 'Отличная стойка, удобная и устойчивая.' },
            { name: 'Юлия', date: '2025-02-27', text: 'Легко настраивается, подходит для большинства микрофонов.' },
        ],
        instructions: 'Регулируйте высоту и угол наклона стойки для комфортной работы с микрофоном.',
    },
    {
        category: 'Усилители и ресиверы',
        subcategory: 'Гибридные усилители',
        title: 'Гибридный усилитель Audio Research VSi60',
        slug: 'gibridny-usilitel-audio-research-vsi60',
        price: '399999',
        image: ['/product/image33.webp', '/product/image34.jpg'],
        count: 5,
        short_description: 'Гибридный усилитель с ламповым и транзисторным выходом.',
        description: 'Комбинированный усилитель для аудиофилов с качественным звучанием.',
        specifications: [
            { title: 'Тип', text: 'Гибридный усилитель' },
            { title: 'Мощность', text: '60 Вт' },
            { title: 'Подключение', text: 'Аналоговое' },
        ],
        reviews: [
            { name: 'Дмитрий', date: '2025-02-20', text: 'Звук просто невероятный, идеально для качественной записи и прослушивания.' },
            { name: 'Юлия', date: '2025-02-21', text: 'Потрясающий усилитель, звучание как в студии.' },
        ],
        instructions: 'Подключите усилитель к вашим колонкам и источникам звука для использования.',
    },
];
